AddonId: KraftAtWork_GogCollectionImporter
Packages:
  - Version: 0.1.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-04-09
    PackageUrl: https://github.com/kraft-at-work/playnite-gog-collection-importer-plugin/releases/download/0.1.1/KraftAtWork_GogCollectionImporter_0_1_1.pext
    Changelog:
      - Non-Gog games from gog
