AddonId: Yalgrin_SteamCollectionImporter
Packages:
  - Version: 0.1.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2026-01-11
    PackageUrl: https://github.com/Yalgrin/playnite-steam-collection-importer-plugin/releases/download/0.1.0/Yalgrin_SteamCollectionImporter_0_1_0.pext
    Changelog:
      - Initial release